version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-delivery-service-netology}
  deliveryservice:
    build: .
    restart: always
    ports:
      - 3000:3001
    environment:
      - PORT=3000
      - DB_NAME=${DB_NAME:-delivery-service-netology}
      - DB_HOST=mongodb://mongo:27017
    depends_on:
      - mongo
